name = "gemini-api-proxy"
main = "worker.js"
compatibility_date = "2024-03-27"

[build]
command = ""

[build.upload]
format = "modules"
main = "./worker.js"
dir = "."

[vars]
GEMINI_API_KEY = "AIzaSyBf6ICQAxR9eA1idY3jr2lrRIBJHc76Q8Y"  # This will be replaced with a secret

[[kv_namespaces]]
binding = "CHAT_HISTORY"
id = "8de4b31c06e14626bb317ad4e4f3124a"
preview_id = "chat-history"

[[d1_databases]]
binding = "DB"
database_name = "videoshare-db"
database_id = "0d724365-ba90-459c-9e05-7a4bdd179b9a" 